In [1]:
import torch

In [21]:
tensor_path = "/home/max/Studium/Leipzig/Semster6/Math_and_ML/math-ml/experiments/baseline_llama3_100/output_2025-06-25_17-06.pt"

exp_results = torch.load(tensor_path)

In [22]:
exp_results.keys()

dict_keys(['prompt0', 'prompt1', 'prompt2', 'prompt3', 'prompt4', 'prompt5', 'prompt6', 'prompt7', 'prompt8', 'prompt9', 'prompt10', 'prompt11', 'prompt12', 'prompt13', 'prompt14', 'prompt15', 'prompt16', 'prompt17', 'prompt18', 'prompt19', 'prompt20', 'prompt21', 'prompt22', 'prompt23', 'prompt24', 'prompt25', 'prompt26', 'prompt27', 'prompt28', 'prompt29', 'prompt30', 'prompt31', 'prompt32', 'prompt33', 'prompt34', 'prompt35', 'prompt36', 'prompt37', 'prompt38', 'prompt39', 'prompt40', 'prompt41', 'prompt42', 'prompt43', 'prompt44', 'prompt45', 'prompt46', 'prompt47', 'prompt48', 'prompt49', 'prompt50', 'prompt51', 'prompt52', 'prompt53', 'prompt54', 'prompt55', 'prompt56', 'prompt57', 'prompt58', 'prompt59', 'prompt60', 'prompt61', 'prompt62', 'prompt63', 'prompt64', 'prompt65', 'prompt66', 'prompt67', 'prompt68', 'prompt69', 'prompt70', 'prompt71', 'prompt72', 'prompt73', 'prompt74', 'prompt75', 'prompt76', 'prompt77', 'prompt78', 'prompt79', 'prompt80', 'prompt81', 'prompt82', 'pr

In [23]:
exp_results['prompt0'].keys()

dict_keys(['generated_tokens', 'decoded_tokens', 'top_p_tokens', 'top_p_logits', 'top_p_probs', 'prompt', 'question', 'ground_truth', 'latency'])

In [43]:
prompt = 'prompt52'
print(f"Answer: {' '.join(exp_results[prompt]['decoded_tokens'])}")
print()
print(exp_results[prompt]['ground_truth'])

Answer:  
 Answer  the  next  question  directly  without  a  unit .
 Do  not  return  any  preamble ,  explanation ,  or  reasoning .  
 Q

30 comic books weigh 7.5 pounds because 30 x .25 = <<30*.25=7.5>>7.5
He needs to remove 7.5 more pounds because 15 - 7.5 = <<15-7.5=7.5>>7.5
He needs to remove 15 toys because 7.5 / .5 = <<15=15>>15
#### 15


In [ ]:
exp_results['prompt0']['top_p_probs']

In [7]:
exp_results['prompt0']['top_p_tokens']

[tensor([   185,     32,    207, 100001,    338,    459,    334,     27,  35829,
           1724,   3132,    363]),
 tensor([    32,    185,     27,  32349, 100001,     48,      3,      7,    549,
             16,     40,     64,   7900,    338,   2819,   1847,   2640,   3539,
           9081,     12,     17,   2960,   1567,    207,  90155,   4622,  95991,
           3673,   2054,    774,  28439,  43778,  78268,     20,     33,     18,
          99297,   4453,   4160,  11912,      9,   6017,     35,     34,   1988,
             19,     21]),
 tensor([25]),
 tensor([   363,     16,     17,    207,     19,     23,     18,     21,     20,
             22,     24,  40804,   8763,     15,    185,  12900,    570,  14957,
           2943,  12034,   4622,    334,     32,   3539,  15718,   1862,      3,
           2130,    338,    628,    549,   9313,   1847, 100001,   1202,   2819,
          10895,    459,    429,   1273,     40,  35829,     35,   2721,    774,
           1724,     33,  28625,

In [8]:
exp_results['prompt0']['generated_tokens']

tensor([185,  32,  25,  23,  27,  68, 378])

In [9]:
len(exp_results['prompt0']['decoded_tokens'])

7

In [30]:
raw_test = 'The answer is 72.0'
test = 72.0

In [28]:
reverse = test[::-1]
print(reverse)

cba


In [34]:
test = str(test)
raw_test_rvs = raw_test[::-1]
for char in test:
    for idx,char_b in enumerate(raw_test_rvs):
        if char == char_b:
            indice = len(raw_test_rvs) - idx -1
            print(indice)
            break

14
15
16
17
