In [2]:
import torch

In [3]:
tensor_path = "/home/max/Studium/Leipzig/Semster6/Math_and_ML/math-ml/experiments/cod_test_json_deepseek/output_2025-06-27_11-46.pt"

exp_results = torch.load(tensor_path)

In [4]:
exp_results.keys()

dict_keys(['prompt0', 'prompt1', 'prompt2', 'prompt3', 'prompt4', 'prompt5', 'prompt6', 'prompt7', 'prompt8', 'prompt9', 'prompt10', 'prompt11', 'prompt12', 'prompt13', 'prompt14', 'prompt15', 'prompt16', 'prompt17', 'prompt18', 'prompt19'])

In [5]:
exp_results['prompt0'].keys()

dict_keys(['generated_tokens', 'decoded_tokens', 'top_p_tokens', 'top_p_logits', 'top_p_probs', 'prompt', 'question', 'ground_truth', 'latency'])

In [5]:
for prompt_key in exp_results.keys():
    answer = ' '.join(exp_results[prompt_key]['decoded_tokens'])
    print(answer)
    print('---')

<｜end▁of▁sentence｜>
---

 What  does  a  brace  take ? 
 What  does  a  coat  take ? 
 What  does  a  hat  take
---

 {' answer ':   2 2 0 0 0 0 . 0 }
---

 {' answer ':   1 8 0 0 }
---

 {' answer ':   4 0 }
---

 {' answer ':   6 3 }
---

 {' answer ':   3 0 }
---

 {' answer ':   8 }
---

 {' answer ':   8 1 }
---

 {" answer ":   6 3 . 0 }
---

 {  " answer ":   9 3  }
---

 Your  solution  should  just  return  the  unit  price  if  you  did  not  buy  the 
 same  number  of  don
---

 {' answer ':   6 }
---
<｜end▁of▁sentence｜>
---

 How  many  interesting  problems  remain ? 
 How  many  problems  remain  that  look  like  ( A , B )?
---

 {' answer ':   7 2 5 }
---
{' answer ':   2 3 0 }
---

 {' answer ':   8 4 0 0 0 }
---

 {' answer ':   3 }
---

 {' answer ':   2 }
---

 {' answer ':   5 4 }
---

 {" answer ":   7 }
---
<｜end▁of▁sentence｜>
---

 {' answer ':   5 }
---

 /* js lint  de vel :  true ,  white :  true  */ 
 /* js lint  indent :  
---

 {" answer ": 5 . 5 }
---

 

In [11]:
prompt = 'prompt3'
print(f"Answer: {' '.join(exp_results[prompt]['decoded_tokens'])}")
print()
print(exp_results[prompt]['ground_truth'])

Answer: # 2 7 0 
 
 } 
 
 ####  Pre - defined  helpers 
 
 ###  const  helpers  =  require (' @ wo oz ing / rich : context - kit ') 
 
 # Use  context  model  to  declare  condition  logic 
 
 helpers . use (' create Condition From Map ') 
 
 # Use  context  model  to  write  sql  query  and  parse  result  ( model  return  raw  data ,  model  fit  with  Rich  or  Flow  database ) 
 
 helpers . use (' create Sql Queries From Map ') 
 
 # use  human ized  time  period  and  date  to  format  time  range 
 
 helpers . use (' time Period And Date Helper ') 
 
 # Use  context  model  to  integrate  logic  function  by  JSON  path  ( flow  database ) 
 
 helpers . use (' flow Json Path Functions ') 
 
 
 ##  Running  the  app 
 
 ``` 
 
 Then  do  $ go  run  query . go  queries . go  Load s  into  memory  the  database  and  the  query  app  prints  queries  in  a  human - readable  way . 
 
 The  query  app  only  can  ask  database  about  loaded  or  cached  data  ( it  does  not  reques

In [ ]:
exp_results['prompt0']['top_p_probs']

In [7]:
exp_results['prompt0']['top_p_tokens']

[tensor([   185,     32,    207, 100001,    338,    459,    334,     27,  35829,
           1724,   3132,    363]),
 tensor([    32,    185,     27,  32349, 100001,     48,      3,      7,    549,
             16,     40,     64,   7900,    338,   2819,   1847,   2640,   3539,
           9081,     12,     17,   2960,   1567,    207,  90155,   4622,  95991,
           3673,   2054,    774,  28439,  43778,  78268,     20,     33,     18,
          99297,   4453,   4160,  11912,      9,   6017,     35,     34,   1988,
             19,     21]),
 tensor([25]),
 tensor([   363,     16,     17,    207,     19,     23,     18,     21,     20,
             22,     24,  40804,   8763,     15,    185,  12900,    570,  14957,
           2943,  12034,   4622,    334,     32,   3539,  15718,   1862,      3,
           2130,    338,    628,    549,   9313,   1847, 100001,   1202,   2819,
          10895,    459,    429,   1273,     40,  35829,     35,   2721,    774,
           1724,     33,  28625,

In [8]:
exp_results['prompt1']['generated_tokens']

tensor([   429,   3510,   1023,    330,  10372,    279,  52181,     11,    441,
          3073,     13,    185,   1567,   2512,  27000,    245,   1525,    280,
         34417,   1437,    279,    245,   2512,    285,   4400,   4807,     11,
           327,   2203,     25,    185,     58,     20,     11,    207,     21,
            11,    207,     18,     11,    207,     20,     60,   1501,  13483,
           825,     20,     11,    207,     21,     11,    207,     18,     11,
           207,     20,     60,    185,     58,     20,     11,    207,     21,
            11,    207,     18,     11,    207,     20,     60,      2,  13483,
           825,     20,     11,    207,     21,     11,    207,     18,     11,
           207,     20,     60,    185, 100001])

In [9]:
len(exp_results['prompt0']['decoded_tokens'])

7

In [30]:
raw_test = 'The answer is 72.0'
test = 72.0

In [28]:
reverse = test[::-1]
print(reverse)

cba


In [34]:
test = str(test)
raw_test_rvs = raw_test[::-1]
for char in test:
    for idx,char_b in enumerate(raw_test_rvs):
        if char == char_b:
            indice = len(raw_test_rvs) - idx -1
            print(indice)
            break

14
15
16
17


In [11]:
import re

In [ ]:
string1 = "abcde"
print(re.search(r'\{\s*["\']answer["\']\s*:\s*[-]?\d+(\.\d+)?\s*\}', string1))

None


In [14]:
string2 = "{could be a json}"
print(re.search(r'\{\s*["\']answer["\']\s*:\s*[-]?\d+(\.\d+)?\s*\}', string2))

None


In [15]:
string3 = "{'answer:' 78}"
print(re.search(r'\{\s*["\']answer["\']\s*:\s*[-]?\d+(\.\d+)?\s*\}', string3))

None


In [16]:
string4 = "{'answer': 78}"
print(re.search(r'\{\s*["\']answer["\']\s*:\s*[-]?\d+(\.\d+)?\s*\}', string4))

<re.Match object; span=(0, 14), match="{'answer': 78}">


In [82]:
string5 = "Just  output  the  answer  in  JSON  format. {' answer ':   9 }"
print(re.search(r'\{\s*["\']answer["\']\s*:\s*[-]?\d+(\.\d+)?\s*\}', string5))

None
