In [64]:
import torch

In [83]:
tensor_path = "/home/max/Studium/Leipzig/Semster6/Math_and_ML/math-ml/experiments/test_json_llama3/output_2025-06-26_16-10.pt"

exp_results = torch.load(tensor_path)

In [84]:
exp_results.keys()

dict_keys(['prompt0', 'prompt1', 'prompt2', 'prompt3', 'prompt4', 'prompt5', 'prompt6', 'prompt7', 'prompt8', 'prompt9', 'prompt10', 'prompt11', 'prompt12', 'prompt13', 'prompt14', 'prompt15', 'prompt16', 'prompt17', 'prompt18', 'prompt19', 'prompt20', 'prompt21', 'prompt22', 'prompt23', 'prompt24', 'prompt25', 'prompt26', 'prompt27', 'prompt28', 'prompt29', 'prompt30', 'prompt31', 'prompt32', 'prompt33', 'prompt34', 'prompt35', 'prompt36', 'prompt37', 'prompt38', 'prompt39', 'prompt40', 'prompt41', 'prompt42', 'prompt43', 'prompt44', 'prompt45', 'prompt46', 'prompt47', 'prompt48', 'prompt49'])

In [85]:
exp_results['prompt0'].keys()

dict_keys(['generated_tokens', 'decoded_tokens', 'top_p_tokens', 'top_p_logits', 'top_p_probs', 'prompt', 'question', 'ground_truth', 'latency'])

In [86]:
for prompt_key in exp_results.keys():
    answer = ' '.join(exp_results[prompt_key]['decoded_tokens'])
    print(answer)
    print('---')

 Answer  by  using  the  round  module .
 {' answer ':   47 . 0 }

---
{' answer ':   4 . 5 }
---
 {' answer ':   102 50 }

---
<|end_of_text|>
---
{' answer ':   7 }

---
{' answer ':   84 . 0 }

---
'''
 {' answer ':   90 }

---
 If  the  player  writes  time  in  minutes ,  the  gr ader  won 't  give  the  player  any  point  even  it
---
   Assume  that  John  could  change  directions  safely  at  a  stop light .
 { “ answer ”:  “ 50 .
---
<|end_of_text|>
---
<|end_of_text|>
---
{' answer ':   150 }

---
{' answer ':   7 }

---
<|end_of_text|>
---
Do  not  use  unit (s ) <|end_of_text|>
---
 ( For  this  scenario ,  money  is  both  lost  and  made  in  increments  of  $ 1 )
 {' answer ':
---
 If  their  total  distance  traveled  was   420  miles ,  what  was  the  number  of  miles  each  train  covered  for
---
{" answer ":   750 0 }

---
 {' answer ':   4 }

---
{' answer ':   5 }

---
 {' answer ':   17 }
---
<|end_of_text|>
---
<|end_of_text|>
---
{' answer ':   6 }

---
<|e

In [68]:
prompt = 'prompt0'
print(f"Answer: {' '.join(exp_results[prompt]['decoded_tokens'])}")
print()
print(exp_results[prompt]['ground_truth'])

Answer: {' answer ':   50 }


Janet sells 16 - 3 - 4 = <<16-3-4=9>>9 duck eggs a day.
She makes 9 * 2 = $<<9*2=18>>18 every day at the farmer’s market.
#### 18


In [ ]:
exp_results['prompt0']['top_p_probs']

In [7]:
exp_results['prompt0']['top_p_tokens']

[tensor([   185,     32,    207, 100001,    338,    459,    334,     27,  35829,
           1724,   3132,    363]),
 tensor([    32,    185,     27,  32349, 100001,     48,      3,      7,    549,
             16,     40,     64,   7900,    338,   2819,   1847,   2640,   3539,
           9081,     12,     17,   2960,   1567,    207,  90155,   4622,  95991,
           3673,   2054,    774,  28439,  43778,  78268,     20,     33,     18,
          99297,   4453,   4160,  11912,      9,   6017,     35,     34,   1988,
             19,     21]),
 tensor([25]),
 tensor([   363,     16,     17,    207,     19,     23,     18,     21,     20,
             22,     24,  40804,   8763,     15,    185,  12900,    570,  14957,
           2943,  12034,   4622,    334,     32,   3539,  15718,   1862,      3,
           2130,    338,    628,    549,   9313,   1847, 100001,   1202,   2819,
          10895,    459,    429,   1273,     40,  35829,     35,   2721,    774,
           1724,     33,  28625,

In [ ]:
exp_results['prompt0']['generated_tokens']

6

In [9]:
len(exp_results['prompt0']['decoded_tokens'])

7

In [30]:
raw_test = 'The answer is 72.0'
test = 72.0

In [28]:
reverse = test[::-1]
print(reverse)

cba


In [34]:
test = str(test)
raw_test_rvs = raw_test[::-1]
for char in test:
    for idx,char_b in enumerate(raw_test_rvs):
        if char == char_b:
            indice = len(raw_test_rvs) - idx -1
            print(indice)
            break

14
15
16
17


In [11]:
import re

In [ ]:
string1 = "abcde"
print(re.search(r'\{\s*["\']answer["\']\s*:\s*[-]?\d+(\.\d+)?\s*\}', string1))

None


In [14]:
string2 = "{could be a json}"
print(re.search(r'\{\s*["\']answer["\']\s*:\s*[-]?\d+(\.\d+)?\s*\}', string2))

None


In [15]:
string3 = "{'answer:' 78}"
print(re.search(r'\{\s*["\']answer["\']\s*:\s*[-]?\d+(\.\d+)?\s*\}', string3))

None


In [16]:
string4 = "{'answer': 78}"
print(re.search(r'\{\s*["\']answer["\']\s*:\s*[-]?\d+(\.\d+)?\s*\}', string4))

<re.Match object; span=(0, 14), match="{'answer': 78}">


In [82]:
string5 = "Just  output  the  answer  in  JSON  format. {' answer ':   9 }"
print(re.search(r'\{\s*["\']answer["\']\s*:\s*[-]?\d+(\.\d+)?\s*\}', string5))

None
