In [64]:
import torch

In [65]:
tensor_path = "/home/max/Studium/Leipzig/Semster6/Math_and_ML/math-ml/experiments/llama3_test_json/output_2025-06-26_15-43.pt"

exp_results = torch.load(tensor_path)

In [66]:
exp_results.keys()

dict_keys(['prompt0'])

In [67]:
exp_results['prompt0'].keys()

dict_keys(['generated_tokens', 'decoded_tokens', 'top_p_tokens', 'top_p_logits', 'top_p_probs', 'prompt', 'question', 'ground_truth', 'latency'])

In [68]:
prompt = 'prompt0'
print(f"Answer: {' '.join(exp_results[prompt]['decoded_tokens'])}")
print()
print(exp_results[prompt]['ground_truth'])

Answer: {' answer ':   50 }


Janet sells 16 - 3 - 4 = <<16-3-4=9>>9 duck eggs a day.
She makes 9 * 2 = $<<9*2=18>>18 every day at the farmer’s market.
#### 18


In [ ]:
exp_results['prompt0']['top_p_probs']

In [7]:
exp_results['prompt0']['top_p_tokens']

[tensor([   185,     32,    207, 100001,    338,    459,    334,     27,  35829,
           1724,   3132,    363]),
 tensor([    32,    185,     27,  32349, 100001,     48,      3,      7,    549,
             16,     40,     64,   7900,    338,   2819,   1847,   2640,   3539,
           9081,     12,     17,   2960,   1567,    207,  90155,   4622,  95991,
           3673,   2054,    774,  28439,  43778,  78268,     20,     33,     18,
          99297,   4453,   4160,  11912,      9,   6017,     35,     34,   1988,
             19,     21]),
 tensor([25]),
 tensor([   363,     16,     17,    207,     19,     23,     18,     21,     20,
             22,     24,  40804,   8763,     15,    185,  12900,    570,  14957,
           2943,  12034,   4622,    334,     32,   3539,  15718,   1862,      3,
           2130,    338,    628,    549,   9313,   1847, 100001,   1202,   2819,
          10895,    459,    429,   1273,     40,  35829,     35,   2721,    774,
           1724,     33,  28625,

In [ ]:
exp_results['prompt0']['generated_tokens']

6

In [9]:
len(exp_results['prompt0']['decoded_tokens'])

7

In [30]:
raw_test = 'The answer is 72.0'
test = 72.0

In [28]:
reverse = test[::-1]
print(reverse)

cba


In [34]:
test = str(test)
raw_test_rvs = raw_test[::-1]
for char in test:
    for idx,char_b in enumerate(raw_test_rvs):
        if char == char_b:
            indice = len(raw_test_rvs) - idx -1
            print(indice)
            break

14
15
16
17


In [11]:
import re

In [ ]:
string1 = "abcde"
print(re.search(r'\{\s*["\']answer["\']\s*:\s*[-]?\d+(\.\d+)?\s*\}', string1))

None


In [14]:
string2 = "{could be a json}"
print(re.search(r'\{\s*["\']answer["\']\s*:\s*[-]?\d+(\.\d+)?\s*\}', string2))

None


In [15]:
string3 = "{'answer:' 78}"
print(re.search(r'\{\s*["\']answer["\']\s*:\s*[-]?\d+(\.\d+)?\s*\}', string3))

None


In [16]:
string4 = "{'answer': 78}"
print(re.search(r'\{\s*["\']answer["\']\s*:\s*[-]?\d+(\.\d+)?\s*\}', string4))

<re.Match object; span=(0, 14), match="{'answer': 78}">


In [18]:
string5 = '{"answer": 78}'
print(re.search(r'\{\s*["\']answer["\']\s*:\s*[-]?\d+(\.\d+)?\s*\}', string5))

<re.Match object; span=(0, 14), match='{"answer": 78}'>
